### ISSUE TITLE
There are errors before "Resetting OS image base."

### ISSUE THREAD

**Issue by shidalao** [adavak/Win_ISO_Patching_Scripts#12]
rt,
![errors](https://github.com/adavak/Win_ISO_Patching_Scripts/assets/127720822/836fee44-25d0-4286-beac-e55ec9369ce1)

**Comment by adavak** [comment]
ok ,let me see

**Comment by adavak** [comment]
https://github.com/adavak/Win_ISO_Patching_Scripts/commit/85b9d4c0577a4569c2cff0605e46d8dec9d396e7

shoud be fine.

**Comment by adavak** [comment]
https://github.com/adavak/Win_ISO_Patching_Scripts/releases/tag/v2023.8b_newformat2

no more error this issue will be close after 24 hours.
