### ISSUE TITLE
nosuggapp = 0 安装后怎么解除

### ISSUE THREAD

**Issue by wpf973** [adavak/Win_ISO_Patching_Scripts#13]
nosuggapp = 0 安装后怎么解除

**Comment by adavak** [comment]
看代码，被修改的注册表键值改为1，话说为啥要解除……

**Comment by adavak** [comment]
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager

下的键值

**Comment by adavak** [comment]
如无其他问题，此问题24小时后关闭。
