### ISSUE TITLE
关于中文版本名称乱码问题

### ISSUE THREAD

**Issue by celetor** [adavak/Win_ISO_Patching_Scripts#14]
`AutoStart=0`对于多版本映像，脚本运行后，按"8"选择版本，此时显示的版本为乱码。
![image](https://github.com/adavak/Win_ISO_Patching_Scripts/assets/86599970/56904d66-0872-44fc-a9d1-6faac0b2b0b5)

**Comment by adavak** [comment]
Start.cmd 下 112行：

:START_WORKWORK
后面加一个
```chcp 936```

**Comment by celetor** [comment]
增加chcp 936后可以了，谢谢
