### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by wpf973** [adavak/Win_ISO_Patching_Scripts#19]
![image](https://github.com/adavak/Win_ISO_Patching_Scripts/assets/22835238/c77900d4-7990-48b9-a72e-309e7e4f6632)
SW_DVD9_WIN_ENT_LTSC_2021_64BIT_ChnSimp_MLF_X22-84402

**Comment by adavak** [comment]
重新运行，保证开始时 patch 文件夹清洁。
