### ISSUE TITLE
ARM64 support!

### ISSUE THREAD

**Issue by shidalao** [adavak/Win_ISO_Patching_Scripts#21]
rt
`Not support this version ISO. or the ISO file error`
`Version: 19041, Architecture: arm64`

**Comment by adavak** [comment]
get the https://github.com/adavak/Win_ISO_Patching_Scripts/archive/refs/heads/master.zip to test for arm64 works.

**Comment by adavak** [comment]
this comment will be close after 24 hours if no reply.
