### ISSUE TITLE
12代，48GB内存，2TB硬盘。Windows11系统。更新了一个23H2镜像，更新了一天了还没好，有进度，但是也太慢了？

### ISSUE THREAD

**Issue by scorpioAnsion** [adavak/Win_ISO_Patching_Scripts#29]
![IMG_3246](https://github.com/user-attachments/assets/43f501c1-4a6c-4424-88d9-6a792df0b29e)
每一个进度条都会走，但是每一步骤都很慢，换了几台电脑都一样。试过的电脑装的系统都是Windows11，镜像都是官方镜像 Windows 11 21H2跟23H2。

但是uupdump的就很正常，个小时内就完成了。

**Comment by adavak** [comment]
就是很慢，如果选择单一版本的话也不至于那么慢。更新速度无法控制。
