### ISSUE TITLE
咨询如何修改脚本Converting install.wim to install.esd时使用的cpu线程限制？

### ISSUE THREAD

**Issue by xdm2211** [adavak/Win_ISO_Patching_Scripts#30]
============================================================
Converting install.wim to install.esd ...
============================================================

[WARNING] Wanted to use 12 threads, but limiting to 2 to fit in available memory!
Using LZMS compression with 2 threads

在这一步转换的时候，脚本限制了只能使用2个线程，转换效率有点慢，请问如何修改实现更多CPU线程一起使用？
因为还有一台服务器具有更多线程和内存，所以想更快实现转换效率，谢谢！
![QQ截图20241113145222](https://github.com/user-attachments/assets/cca53e4e-7d2f-4fe8-9242-5742d0f1b263)

**Comment by adavak** [comment]
修改不了，这是 wimlib 的限制，尝试代码按照指导加入 `=threads=8` 并不管用。还是被降到2。

**Comment by xdm2211** [comment]
> 修改不了，这是 wimlib 的限制，尝试代码按照指导加入 `--threads=8` 并不管用。还是被降到2。

经过测试该问题已经解决。问题出在脚本内置的wimlib-imagex.exe版本原因，因为该文件为32位构建版本，所以限制了线程数，替换为wimlib-1.14.4-windows-x86_64-bin.zip内的X64版本后问题解决。
![QQ截图20241115174649](https://github.com/user-attachments/assets/a7c56854-464e-4abf-a98c-015f19e43b08)
