### ISSUE TITLE
建议加入更多解码器

### ISSUE THREAD

**Issue by LennoC** [adavak/Win_ISO_Patching_Scripts#31]
希望能通过脚本预置更多的解码器。甚至可以考虑加入部分UWP，例如为LTSC预置Windows Store等。
常见的HEIF和HEVC解码器，这两个现在自己加入需要想办法手动下载，没办法在商店里直接加的，能预置集成的话更好。
列表: （来自UUP DUMP）
Microsoft.WebMediaExtensions_8wekyb3d8bbwe
Microsoft.RawImageExtension_8wekyb3d8bbwe
Microsoft.HEIFImageExtension_8wekyb3d8bbwe
Microsoft.HEVCVideoExtension_8wekyb3d8bbwe
Microsoft.VP9VideoExtensions_8wekyb3d8bbwe
Microsoft.WebpImageExtension_8wekyb3d8bbwe
Microsoft.DolbyAudioExtensions_8wekyb3d8bbwe
Microsoft.AVCEncoderVideoExtension_8wekyb3d8bbwe
Microsoft.MPEG2VideoExtension_8wekyb3d8bbwe
Microsoft.AV1VideoExtension_8wekyb3d8bbwe

**Comment by adavak** [comment]
要不是 ltsc 因为 vp9 是必要的功能设置缺失，vp9 我都不想加。

ltsc 就是无 store 的，不要试图把其变成普通版，与其这样不如直接用普通版。
